C++ Proxy Server: Logger Class Reference
Logger Class Reference
#include <logger.hpp>
Public Types
enum class LogLevel { DEBUG , INFO , WARNING , ERROR }
Public Member Functions
void debug (const std::string &message)
void info (const std::string &message)
void warning (const std::string &message)
void error (const std::string &message)
Static Public Member Functions
static Logger & get_instance ()
Private Member Functions
Logger ()
~Logger ()
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
void log (LogLevel level, const std::string &message)
std::string get_timestamp ()
Private Attributes
std::ofstream log_file_
Detailed Description
Definition at line 7 of file logger.hpp.
Member Enumeration Documentation
LogLevel
enum class Logger::LogLevel strong
Enumerator
DEBUG
INFO
WARNING
ERROR
Definition at line 9 of file logger.hpp.
{
        DEBUG,
        INFO,
        WARNING,
        ERROR
    };
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger () private
Definition at line 14 of file logger.cpp.
               {
    // Get the build directory path
    auto build_dir = std::filesystem::current_path();
    auto logs_dir = build_dir / "logs";
    auto log_file_path = logs_dir / "proxy.log";
    // Create logs directory if it doesn't exist
    std::filesystem::create_directories(logs_dir);
    // Open log file
    log_file_.open(log_file_path, std::ios::app);
}
References log_file_.
Referenced by get_instance(), Logger(), and operator=().
~Logger()
Logger::~Logger () private
Definition at line 27 of file logger.cpp.
                {
    if (log_file_.is_open()) {
        log_file_.close();
    }
}
References log_file_.
Logger() [2/2]
Logger::Logger (const Logger &) private delete
References Logger().
Member Function Documentation
debug()
void Logger::debug (const std::string & message)
Definition at line 70 of file logger.cpp.
{
    log(LogLevel::DEBUG, message);
}
References DEBUG, and log().
Referenced by ProxyServer::handle_connection(), and FilterManager::is_blocked().
error()
void Logger::error (const std::string & message)
Definition at line 82 of file logger.cpp.
{
    log(LogLevel::ERROR, message);
}
References ERROR, and log().
Referenced by ProxyServer::accept_connections(), ProxyServer::create_target_connection(), ProxyServer::handle_connection(), ProxyServer::initialize_socket(), and ProxyServer::tunnel_connection().
get_instance()
Logger & Logger::get_instance () static
Definition at line 9 of file logger.cpp.
{
    static Logger instance;
    return instance;
}
References Logger().
Referenced by ProxyServer::accept_connections(), FilterManager::add_blacklist_entry(), ProxyServer::create_target_connection(), ProxyServer::handle_connection(), ProxyServer::initialize_socket(), FilterManager::is_blocked(), ProxyServer::ProxyServer(), FilterManager::remove_blacklist_entry(), FilterManager::set_blacklist_mode(), ProxyServer::start(), ProxyServer::stop(), and ProxyServer::tunnel_connection().
get_timestamp()
std::string Logger::get_timestamp () private
Definition at line 33 of file logger.cpp.
{
    auto now = std::chrono::system_clock::now();
    auto time = std::chrono::system_clock::to_time_t(now);
    std::stringstream ss;
    ss << std::put_time(std::localtime(&time), "%Y-%m-%d %H:%M:%S");
    return ss.str();
}
Referenced by log().
info()
void Logger::info (const std::string & message)
Definition at line 74 of file logger.cpp.
{
    log(LogLevel::INFO, message);
}
References INFO, and log().
Referenced by FilterManager::add_blacklist_entry(), ProxyServer::handle_connection(), ProxyServer::initialize_socket(), FilterManager::is_blocked(), ProxyServer::ProxyServer(), FilterManager::remove_blacklist_entry(), FilterManager::set_blacklist_mode(), ProxyServer::start(), and ProxyServer::stop().
log()
void Logger::log (LogLevel level, const std::string & message) private
Definition at line 41 of file logger.cpp.
{
    std::string level_str;
    switch (level) {
        case LogLevel::DEBUG:
            level_str = "DEBUG";
            break;
        case LogLevel::INFO:
            level_str = "INFO";
            break;
        case LogLevel::WARNING:
            level_str = "WARNING";
            break;
        case LogLevel::ERROR:
            level_str = "ERROR";
            break;
    }
    std::string log_message = get_timestamp() + " [" + level_str + "] " + message;
    // Console output
    std::cout << log_message << std::endl;
    // File output
    if (log_file_.is_open()) {
        log_file_ << log_message << std::endl;
        log_file_.flush();
    }
}
References DEBUG, ERROR, get_timestamp(), INFO, log_file_, and WARNING.
Referenced by debug(), error(), info(), and warning().
operator=()
Logger & Logger::operator= (const Logger &) private delete
References Logger().
warning()
void Logger::warning (const std::string & message)
Definition at line 78 of file logger.cpp.
{
    log(LogLevel::WARNING, message);
}
References log(), and WARNING.
Member Data Documentation
log_file_
std::ofstream Logger::log_file_ private
Definition at line 32 of file logger.hpp.
Referenced by log(), Logger(), and ~Logger().
The documentation for this class was generated from the following files:
include/logger.hpp
src/logger.cpp