C++ Proxy Server: WebUI Class Reference
WebUI Class Reference
#include <web_ui.hpp>
Public Member Functions
WebUI (uint16_t port, FilterManager &filter_manager)
void start ()
Private Member Functions
std::string generate_dashboard ()
Private Attributes
uint16_t port_
FilterManager & filter_manager_
httplib::Server server_
Detailed Description
Definition at line 7 of file web_ui.hpp.
Constructor & Destructor Documentation
WebUI()
WebUI::WebUI (uint16_t port, FilterManager & filter_manager)
Definition at line 6 of file web_ui.cpp.
    : port_(port), filter_manager_(filter_manager) {}
References filter_manager_, and port_.
Member Function Documentation
generate_dashboard()
std::string WebUI::generate_dashboard () private
Definition at line 36 of file web_ui.cpp.
{
    std::stringstream ss;
    ss << R"DELIM(<!DOCTYPE html>
<html>
<head>
    <title>Blacklist Manager</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .container { max-width: 800px; margin: 0 auto; }
        .card { background: #f5f5f5; padding: 20px; margin: 10px 0; border-radius: 5px; }
        button { background: #4CAF50; color: white; border: none; padding: 10px 20px; border-radius: 3px; cursor: pointer; }
        button:hover { background: #45a049; }
References filter_manager_.
Referenced by start().
start()
void WebUI::start ()
Definition at line 9 of file web_ui.cpp.
                  {
    server_.Get("/", [this](const httplib::Request&, httplib::Response& res) {
        res.set_content(generate_dashboard(), "text/html");
    });
    server_.Post("/add_blacklist", [this](const httplib::Request& req, httplib::Response& res) {
        std::string entry = req.get_param_value("entry");
        filter_manager_.add_blacklist_entry(entry);
        res.set_content("{\"success\":true}", "application/json");
    });
    server_.Post("/remove_blacklist", [this](const httplib::Request& req, httplib::Response& res) {
        std::string entry = req.get_param_value("entry");
        filter_manager_.remove_blacklist_entry(entry);
        res.set_content("{\"success\":true}", "application/json");
    });
    server_.Get("/logs", [this](const httplib::Request&, httplib::Response& res) {
        std::ifstream log_file("logs/proxy.log");
        std::stringstream buffer;
        buffer << log_file.rdbuf();
        res.set_content(buffer.str(), "text/plain");
    });
    server_.listen("0.0.0.0", port_);
}
References filter_manager_, generate_dashboard(), port_, and server_.
Referenced by main().
Member Data Documentation
filter_manager_
FilterManager& WebUI::filter_manager_ private
Definition at line 15 of file web_ui.hpp.
Referenced by generate_dashboard(), start(), and WebUI().
port_
uint16_t WebUI::port_ private
Definition at line 14 of file web_ui.hpp.
Referenced by start(), and WebUI().
server_
httplib::Server WebUI::server_ private
Definition at line 16 of file web_ui.hpp.
Referenced by start().
The documentation for this class was generated from the following files:
include/web_ui.hpp
src/web_ui.cpp