C++ Proxy Server: FilterManager Class Reference
FilterManager Class Reference
#include <filter_manager.hpp>
Public Member Functions
FilterManager ()
~FilterManager ()=default
void add_blacklist_entry (const std::string &entry)
void remove_blacklist_entry (const std::string &entry)
const std::set< std::string > & get_blacklist () const
void set_blacklist_mode (bool enabled)
bool is_blacklist_mode () const
bool is_blocked (const std::string &url) const
Private Attributes
std::set< std::string > blacklist_
bool blacklist_mode_
Detailed Description
Definition at line 7 of file filter_manager.hpp.
Constructor & Destructor Documentation
FilterManager()
FilterManager::FilterManager ()
Definition at line 5 of file filter_manager.cpp.
: blacklist_mode_(false) {}
References blacklist_mode_.
~FilterManager()
FilterManager::~FilterManager () default
Member Function Documentation
add_blacklist_entry()
void FilterManager::add_blacklist_entry (const std::string & entry)
Definition at line 12 of file filter_manager.cpp.
{
    blacklist_.insert(entry);
    Logger::get_instance().info("Added blacklist entry: " + entry);
}
References blacklist_, Logger::get_instance(), and Logger::info().
get_blacklist()
const std::set< std::string > & FilterManager::get_blacklist () const inline
Definition at line 15 of file filter_manager.hpp.
{ return blacklist_; }
References blacklist_.
is_blacklist_mode()
bool FilterManager::is_blacklist_mode () const inline
Definition at line 17 of file filter_manager.hpp.
{ return blacklist_mode_; }
References blacklist_mode_.
is_blocked()
bool FilterManager::is_blocked (const std::string & url) const
Definition at line 22 of file filter_manager.cpp.
{
    if (!blacklist_mode_) {
        return false;
    }
    // Extract domain from URL
    std::string domain = url;
    // Remove protocol if present
    size_t protocol_end = domain.find("://");
    if (protocol_end != std::string::npos) {
        domain = domain.substr(protocol_end + 3);
    }
    // Remove path and query parameters
    size_t path_start = domain.find('/');
    if (path_start != std::string::npos) {
        domain = domain.substr(0, path_start);
    }
    // Remove port if present
    size_t port_start = domain.find(':');
    if (port_start != std::string::npos) {
        domain = domain.substr(0, port_start);
    }
    // Remove www. prefix if present
    if (domain.substr(0, 4) == "www.") {
        domain = domain.substr(4);
    }
    Logger::get_instance().debug("Checking domain: " + domain);
    // Check if the domain matches any blacklist entry
    for (const auto& entry : blacklist_) {
        if (domain == entry) {
            Logger::get_instance().info("Domain blocked: " + domain + " (matches blacklist entry: " + entry + ")");
            return true;
        }
    }
    return false;
}
References blacklist_, blacklist_mode_, Logger::debug(), Logger::get_instance(), and Logger::info().
remove_blacklist_entry()
void FilterManager::remove_blacklist_entry (const std::string & entry)
Definition at line 17 of file filter_manager.cpp.
{
    blacklist_.erase(entry);
    Logger::get_instance().info("Removed blacklist entry: " + entry);
}
References blacklist_, Logger::get_instance(), and Logger::info().
set_blacklist_mode()
void FilterManager::set_blacklist_mode (bool enabled)
Definition at line 7 of file filter_manager.cpp.
{
    blacklist_mode_ = enabled;
    Logger::get_instance().info("Blacklist mode " + std::string(enabled ? "enabled" : "disabled"));
}
References blacklist_mode_, Logger::get_instance(), and Logger::info().
Member Data Documentation
blacklist_
std::set<std::string> FilterManager::blacklist_ private
Definition at line 23 of file filter_manager.hpp.
Referenced by add_blacklist_entry(), get_blacklist(), is_blocked(), and remove_blacklist_entry().
blacklist_mode_
bool FilterManager::blacklist_mode_ private
Definition at line 24 of file filter_manager.hpp.
Referenced by FilterManager(), is_blacklist_mode(), is_blocked(), and set_blacklist_mode().
The documentation for this class was generated from the following files:
include/filter_manager.hpp
src/filter_manager.cpp