C++ Proxy Server: ProxyServer Class Reference
ProxyServer Class Reference
#include <proxy_server.hpp>
Public Member Functions
ProxyServer (uint16_t port, FilterManager &filter_manager)
~ProxyServer ()
void start ()
void stop ()
bool is_running () const
Static Public Attributes
static constexpr int BUFFER_SIZE = 8192
static constexpr int MAX_CONNECTIONS = 100
Private Member Functions
void handle_connection (int client_socket)
void accept_connections ()
bool initialize_socket ()
int create_target_connection (const std::string &host, int port)
void tunnel_connection (int client_socket, int target_socket)
void send_error_response (int socket, const std::string &status)
std::string extract_host_from_request (const std::string &request)
Private Attributes
uint16_t port_
int server_socket_
std::atomic< bool > running_
std::vector< std::thread > worker_threads_
std::mutex mutex_
FilterManager & filter_manager_
Detailed Description
Definition at line 12 of file proxy_server.hpp.
Constructor & Destructor Documentation
ProxyServer()
ProxyServer::ProxyServer (uint16_t port, FilterManager & filter_manager)
Definition at line 14 of file proxy_server.cpp.
    : port_(port), server_socket_(-1), running_(false), filter_manager_(filter_manager) {
    Logger::get_instance().info("Proxy server initialized on port " + std::to_string(port));
    filter_manager_.set_blacklist_mode(true);  // Enable blacklist mode by default
}
References filter_manager_, Logger::get_instance(), Logger::info(), port_, running_, and server_socket_.
~ProxyServer()
ProxyServer::~ProxyServer ()
Definition at line 20 of file proxy_server.cpp.
{
    stop();
}
References stop().
Member Function Documentation
accept_connections()
void ProxyServer::accept_connections () private
Definition at line 86 of file proxy_server.cpp.
{
    while (running_) {
        int client_socket = accept(server_socket_, nullptr, nullptr);
        if (client_socket < 0) {
            if (running_) {
                Logger::get_instance().error("Failed to accept connection");
            }
            continue;
        }
        // Clean up finished threads
        worker_threads_.erase(
            std::remove_if(worker_threads_.begin(), worker_threads_.end(),
                [](std::thread& t) { return !t.joinable(); }),
            worker_threads_.end()
        );
        // Start new thread for handling the connection
        worker_threads_.emplace_back(&ProxyServer::handle_connection, this, client_socket);
    }
}
References Logger::error(), Logger::get_instance(), handle_connection(), running_, server_socket_, and worker_threads_.
Referenced by start().
create_target_connection()
int ProxyServer::create_target_connection (const std::string & host, int port) private
Definition at line 193 of file proxy_server.cpp.
{
    struct addrinfo hints, *result;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    std::string port_str = std::to_string(port);
    if (getaddrinfo(host.c_str(), port_str.c_str(), &hints, &result) != 0) {
        Logger::get_instance().error("Failed to resolve host: " + host);
        return -1;
    }
    int sock = socket(result->ai_family, result->ai_socktype, result->ai_protocol);
    if (sock < 0) {
        freeaddrinfo(result);
        return -1;
    }
    if (connect(sock, result->ai_addr, result->ai_addrlen) < 0) {
        Logger::get_instance().error("Failed to connect to target server");
        close(sock);
        freeaddrinfo(result);
        return -1;
    }
    freeaddrinfo(result);
    return sock;
}
References Logger::error(), and Logger::get_instance().
Referenced by handle_connection().
extract_host_from_request()
std::string ProxyServer::extract_host_from_request (const std::string & request) private
Definition at line 263 of file proxy_server.cpp.
{
    std::regex host_regex("Host:\\s*([^\\r\\n]+)");
    std::smatch match;
    if (std::regex_search(request, match, host_regex)) {
        std::string host = match[1];
        // Remove port if present
        size_t colon_pos = host.find(':');
        if (colon_pos != std::string::npos) {
            host = host.substr(0, colon_pos);
        }
        return host;
    }
    return "";
}
Referenced by handle_connection().
handle_connection()
void ProxyServer::handle_connection (int client_socket) private
Definition at line 108 of file proxy_server.cpp.
{
    char buffer[BUFFER_SIZE];
    int bytes_read = read(client_socket, buffer, sizeof(buffer) - 1);
    if (bytes_read <= 0) {
        Logger::get_instance().error("Failed to read from client socket");
        close(client_socket);
        return;
    }
    buffer[bytes_read] = '\0';
    std::string request(buffer);
    Logger::get_instance().debug("Received request:\n" + request);
    // Parse the request
    std::istringstream request_stream(request);
    std::string method, target, version;
    request_stream >> method >> target >> version;
    if (method == "CONNECT") {
        // Handle HTTPS CONNECT request
        Logger::get_instance().info("Processing HTTPS CONNECT request to: " + target);
        // Parse host and port
        size_t colon_pos = target.find(':');
        if (colon_pos == std::string::npos) {
            Logger::get_instance().error("Invalid CONNECT target format");
            send_error_response(client_socket, "400 Bad Request");
            return;
        }
        std::string host = target.substr(0, colon_pos);
        // Check if the host should be blocked
        if (filter_manager_.is_blocked(host)) {
            Logger::get_instance().info("HTTPS request blocked - host in blacklist: " + host);
            send_error_response(client_socket, "403 Forbidden");
            return;
        }
        int port = std::stoi(target.substr(colon_pos + 1));
        // Create connection to target server
        int target_socket = create_target_connection(host, port);
        if (target_socket < 0) {
            Logger::get_instance().error("Failed to connect to target server: " + host + ":" + std::to_string(port));
            send_error_response(client_socket, "502 Bad Gateway");
            return;
        }
        // Send 200 Connection Established
        std::string response = "HTTP/1.1 200 Connection Established\r\n\r\n";
        if (send(client_socket, response.c_str(), response.length(), 0) < 0) {
            Logger::get_instance().error("Failed to send CONNECT response");
            close(target_socket);
            close(client_socket);
            return;
        }
        // Start bidirectional tunneling
        tunnel_connection(client_socket, target_socket);
    } else {
        // Handle regular HTTP request
        std::string host = extract_host_from_request(request);
        if (host.empty()) {
            Logger::get_instance().error("No host found in request");
            send_error_response(client_socket, "400 Bad Request");
            return;
        }
        // Check if the request should be blocked
        if (filter_manager_.is_blocked(host)) {
            Logger::get_instance().info("HTTP request blocked - host in blacklist: " + host);
            send_error_response(client_socket, "403 Forbidden");
            return;
        }
        // Process HTTP request (implement your HTTP forwarding logic here)
        Logger::get_instance().info("Processing HTTP request: " + method + " " + target);
        send_error_response(client_socket, "501 Not Implemented");
    }
    close(client_socket);
}
References BUFFER_SIZE, create_target_connection(), Logger::debug(), Logger::error(), extract_host_from_request(), filter_manager_, Logger::get_instance(), Logger::info(), send_error_response(), and tunnel_connection().
Referenced by accept_connections().
initialize_socket()
bool ProxyServer::initialize_socket () private
Definition at line 24 of file proxy_server.cpp.
{
    server_socket_ = socket(AF_INET, SOCK_STREAM, 0);
    if (server_socket_ < 0) {
        Logger::get_instance().error("Failed to create socket");
        return false;
    }
    int opt = 1;
    if (setsockopt(server_socket_, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) < 0) {
        Logger::get_instance().error("Failed to set socket options");
        return false;
    }
    struct sockaddr_in address;
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(port_);
    if (bind(server_socket_, (struct sockaddr*)&address, sizeof(address)) < 0) {
        Logger::get_instance().error("Failed to bind socket");
        return false;
    }
    if (listen(server_socket_, MAX_CONNECTIONS) < 0) {
        Logger::get_instance().error("Failed to listen on socket");
        return false;
    }
    Logger::get_instance().info("Socket initialized successfully");
    return true;
}
References Logger::error(), Logger::get_instance(), Logger::info(), MAX_CONNECTIONS, port_, and server_socket_.
Referenced by start().
is_running()
bool ProxyServer::is_running () const
Definition at line 82 of file proxy_server.cpp.
{
    return running_;
}
References running_.
send_error_response()
void ProxyServer::send_error_response (int socket, const std::string & status) private
Definition at line 222 of file proxy_server.cpp.
{
    std::string response = "HTTP/1.1 " + status + "\r\n"
                          "Content-Type: text/plain\r\n"
                          "Content-Length: " + std::to_string(status.length()) + "\r\n\r\n" +
                          status;
    send(socket, response.c_str(), response.length(), 0);
}
Referenced by handle_connection().
start()
void ProxyServer::start ()
Definition at line 56 of file proxy_server.cpp.
{
    if (!initialize_socket()) {
        throw std::runtime_error("Failed to initialize socket");
    }
    running_ = true;
    Logger::get_instance().info("Proxy server started");
    accept_connections();
}
References accept_connections(), Logger::get_instance(), Logger::info(), initialize_socket(), and running_.
Referenced by main().
stop()
void ProxyServer::stop ()
Definition at line 66 of file proxy_server.cpp.
                       {
    running_ = false;
    if (server_socket_ >= 0) {
        close(server_socket_);
        server_socket_ = -1;
    }
    for (auto& thread : worker_threads_) {
        if (thread.joinable()) {
            thread.join();
        }
    }
    worker_threads_.clear();
    Logger::get_instance().info("Proxy server stopped");
}
References Logger::get_instance(), Logger::info(), running_, server_socket_, and worker_threads_.
Referenced by ~ProxyServer().
tunnel_connection()
void ProxyServer::tunnel_connection (int client_socket, int target_socket) private
Definition at line 230 of file proxy_server.cpp.
{
    fd_set read_fds;
    char buffer[BUFFER_SIZE];
    while (true) {
        FD_ZERO(&read_fds);
        FD_SET(client_socket, &read_fds);
        FD_SET(target_socket, &read_fds);
        int max_fd = std::max(client_socket, target_socket);
        if (select(max_fd + 1, &read_fds, nullptr, nullptr, nullptr) < 0) {
            Logger::get_instance().error("Select error in tunnel");
            break;
        }
        // Client to target
        if (FD_ISSET(client_socket, &read_fds)) {
            int bytes = recv(client_socket, buffer, sizeof(buffer), 0);
            if (bytes <= 0) break;
            if (send(target_socket, buffer, bytes, 0) <= 0) break;
        }
        // Target to client
        if (FD_ISSET(target_socket, &read_fds)) {
            int bytes = recv(target_socket, buffer, sizeof(buffer), 0);
            if (bytes <= 0) break;
            if (send(client_socket, buffer, bytes, 0) <= 0) break;
        }
    }
    close(target_socket);
}
References BUFFER_SIZE, Logger::error(), and Logger::get_instance().
Referenced by handle_connection().
Member Data Documentation
BUFFER_SIZE
int ProxyServer::BUFFER_SIZE = 8192 static constexpr
Definition at line 14 of file proxy_server.hpp.
Referenced by handle_connection(), and tunnel_connection().
filter_manager_
FilterManager& ProxyServer::filter_manager_ private
Definition at line 38 of file proxy_server.hpp.
Referenced by handle_connection(), and ProxyServer().
MAX_CONNECTIONS
int ProxyServer::MAX_CONNECTIONS = 100 static constexpr
Definition at line 15 of file proxy_server.hpp.
Referenced by initialize_socket().
mutex_
std::mutex ProxyServer::mutex_ private
Definition at line 37 of file proxy_server.hpp.
port_
uint16_t ProxyServer::port_ private
Definition at line 33 of file proxy_server.hpp.
Referenced by initialize_socket(), and ProxyServer().
running_
std::atomic<bool> ProxyServer::running_ private
Definition at line 35 of file proxy_server.hpp.
Referenced by accept_connections(), is_running(), ProxyServer(), start(), and stop().
server_socket_
int ProxyServer::server_socket_ private
Definition at line 34 of file proxy_server.hpp.
Referenced by accept_connections(), initialize_socket(), ProxyServer(), and stop().
worker_threads_
std::vector<std::thread> ProxyServer::worker_threads_ private
Definition at line 36 of file proxy_server.hpp.
Referenced by accept_connections(), and stop().
The documentation for this class was generated from the following files:
include/proxy_server.hpp
src/proxy_server.cpp